name: build.yml
on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        required: true
        description: 'os'
        options:
          - windows
          - linux
      arch:
        type: choice
        required: true
        description: 'os arch'
        default: 'amd64'
        options:
          - amd64
          - arm64
          - 386
jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: pgdev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Clone and build frontend
        run: |
          git clone https://github.com/komari-monitor/komari-web web
          cd web
          npm install
          npm run build
          cd ..
          mkdir -p public/dist
          cp -r web/dist/* public/dist/

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install Zig cross-compiler toolchain
        run: |
          sudo apt-get update # Update apt package lists
          sudo apt-get install -y build-essential curl
          wget https://ziglang.org/download/0.14.1/zig-x86_64-linux-0.14.1.tar.xz
          sudo tar -C /usr/local -Jxf zig-x86_64-linux-0.14.1.tar.xz
          echo "PATH=$PATH:/usr/local/zig-x86_64-linux-0.14.1" >> $GITHUB_ENV

      - name: Set up the environment
        run: |
          if [ "${{ inputs.os }}" == "windows" ] && [ "${{ inputs.arch }}" == "amd64" ]; then
            echo "ZIG_TARGET_TRIPLE=x86_64-windows-gnu" >> $GITHUB_ENV
          elif [ "${{ inputs.os }}" == "windows" ] && [ "${{ inputs.arch }}" == "arm64" ]; then
            echo "ZIG_TARGET_TRIPLE=aarch64-windows-gnu" >> $GITHUB_ENV
          elif [ "${{ inputs.os }}" == "windows" ] && [ "${{ inputs.arch }}" == "386" ]; then
            echo "ZIG_TARGET_TRIPLE=x86-windows-gnu" >> $GITHUB_ENV
          elif [ "${{ inputs.os }}" == "linux" ] && [ "${{ inputs.arch }}" == "arm64" ]; then
            echo "ZIG_TARGET_TRIPLE=aarch64-linux-musl" >> $GITHUB_ENV
          elif [ "${{ inputs.os }}" == "linux" ] && [ "${{ inputs.arch }}" == "amd64" ]; then
            echo "ZIG_TARGET_TRIPLE=x86_64-linux-musl" >> $GITHUB_ENV
          elif [ "${{ inputs.os }}" == "linux" ] && [ "${{ inputs.arch }}" == "386" ]; then
            echo "ZIG_TARGET_TRIPLE=x86-linux-musl" >> $GITHUB_ENV
          else
            echo "Unsupported OS/ARCH combination" && exit 1
          fi
          if [ "${{ inputs.os }}" == "windows" ]; then
           echo "binary_extension=.exe" >> $GITHUB_ENV
          elif [ "${{ inputs.os }}" == "linux" ]; then
           echo "binary_extension=" >> $GITHUB_ENV
          else
           echo "Unsupported OS/ARCH combination" && exit 1
          fi


      - name: Build binary
        env:
          GOOS: ${{ inputs.os }}
          GOARCH: ${{inputs.arch}}
          CGO_ENABLED: 1
          CC: zig cc -target ${{ env.ZIG_TARGET_TRIPLE }}
          GIN_MODE: release
        run: |
          BINARY_NAME=komari-${{ inputs.goos }}-${{ inputs.goarch }}
          # Append the appropriate executable extension based on the OS
          if [ "${{ env.binary_extension }}" != "" ]; then
            BINARY_NAME=${BINARY_NAME}${{ env.binary_extension }}
          fi
          VERSION="${{ github.sha }}"
          VERSION_HASH="${{ github.sha }}"
          go build -trimpath -ldflags="-s -w -X github.com/komari-monitor/komari/utils.CurrentVersion=${VERSION} -X github.com/komari-monitor/komari/utils.VersionHash=${VERSION_HASH}" -o $BINARY_NAME

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: komari-${{ inputs.goos }}-${{ inputs.goarch }}
          path: komari-${{ inputs.goos }}-${{ inputs.goarch }}*