name: Build & Push to GHCR
on:
  workflow_dispatch

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # owner/repo

jobs:
  push_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'rust'

      - name: run
        run: |
          set -euo pipefail
          TAG=$(curl -s https://api.github.com/repos/smagicalk/komari/releases/latest | grep '"tag_name":' | head -1 | cut -d '"' -f4)
          curl -L  --fail --retry 3 -o komari https://github.com/smagicalk/komari/releases/download/$TAG/komari-linux-amd64
          
          if [ -z "$TAG" ] || [ "$TAG" = "null" ]; then
            echo "❌ 未能获取到最新的release tag"
            exit 1
          fi
          echo "✅ 获取到最新tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_ENV
          
          # 验证文件是否下载成功
          if [ ! -f "komari" ]; then
            echo "❌ komari文件下载失败"
            exit 1
          fi
          
          # 给二进制文件添加可执行权限（关键！）
          chmod +x komari
          echo "✅ 已添加可执行权限"


      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: DockerFile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/smagicalk/komari-pg:${{env.tag}}
            ghcr.io/smagicalk/komari-pg:latest

          
            
            
